#
# Input objects.
#
# Synopsis
# ========
# <object>:
#   count: <n> (number of objects)
#   width: <n> (bit width of object type)
#   coding:
#     <name>: { msb: <n>, lsb: <n> } (object attribuite by MSB:LSB slice)
#

tdf:
  objects:
    muon:
      label: "muon"
      count: 8
      width: 64
      coding:
        spare: { msb: 63, lsb: 36 }
        charge: { msb: 35, lsb: 34 }
        iso: { msb: 33, lsb: 32 }
        eta: { msb: 31, lsb: 23 }
        qual: { msb: 22 , lsb: 19 }
        pt: { msb: 18, lsb: 10 }
        phi: { msb: 9, lsb: 0 }

    eg:
      label: "e/γ"
      count: 12
      width: 32
      coding:
        spare: { msb: 31, lsb: 25 }
        phi: { msb: 24, lsb: 17 }
        eta: { msb: 16, lsb: 9 }
        et: { msb: 8, lsb: 0 }

    tau:
      label: "τ"
      count: 8
      width: 32
      coding:
        phi: { msb: 24, lsb: 17 }
        eta: { msb: 16, lsb: 9 }
        et: { msb: 8, lsb: 0 }

    jet:
      label: "jet"
      count: 12
      width: 32
      coding:
        phi: { msb: 26, lsb: 19 }
        eta: { msb: 18, lsb: 11 }
        et: { msb: 10, lsb: 0 }

    et:
      label: "et"
      count: 1
      width: 32
      coding:
        et: { msb: 11, lsb: 0 }

    ht:
      label: "ht"
      count: 1
      width: 32
      coding:
        et: { msb: 11, lsb: 0 }

    etm:
      label: "et/missing"
      count: 1
      width: 32
      coding:
        phi: { msb: 19, lsb: 12 }
        et: { msb: 11, lsb: 0 }

    htm:
      label: "ht/missing"
      count: 1
      width: 32
      coding:
        phi: { msb: 19, lsb: 12 }
        et: { msb: 11, lsb: 0 }
